routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('verify.invitations')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::middleware('verify.expiration.invitations')->post('/', 'HomeController@complete')->name('complete');
});

Route::prefix('/dashboard')->middleware('auth')->namespace('Dashboard')->name('dashboard.')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::prefix('/invitations')->name('invitations.')->group(function () {
        Route::get('/', 'InvitationController@index')->name('index');
        Route::post('/generate', 'InvitationController@generate')->name('generate');
    });
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Invitation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invitation extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'status_id',
        'user_id',
        'registration_code',
        'expired_at',
        'status_id',
        'completed_at'
    ];

    protected $dates = [
        'expired_at',
        'completed_at'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function status()
    {
        return $this->belongsTo(Status::class);
    }

    public function isValid()
    {
        return $this->status->name === 'pending' && now()->timestamp < $this->expired_at->timestamp;
    }
}

app/Http/Controllers/Api/InvitationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Invitation;
use Illuminate\Http\Request;

class InvitationController extends Controller
{
    public function index(Request $request)
    {
        $search = json_decode($request->search ?: '{}', true);

        $query = Invitation::query()->with(['user', 'status']);

        return response()->json([
            'success' => true,
            'code' => 200,
            'data' => $query->orderBy('id', 'desc')->paginate($request->perPage ?: 10)
        ]);
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/InvitationController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\GenerateInvitationRequest;
use App\Mail\InvitationMail;
use App\Models\Invitation;
use App\Models\Role;
use App\Models\Status;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class InvitationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.invitations.index');
    }

    public function generate(GenerateInvitationRequest $request)
    {
        // store the user first.
        DB::beginTransaction();
        try {
            tap(User::create([
                'role_id' => Role::where('name', 'user')->first()->id,
                'email' => $request->email,
                'password' => Hash::make(Str::random(8)),
            ]), function ($user) {
                Mail::send(new InvitationMail(Invitation::create([
                    'user_id' => $user->id,
                    'status_id' => Status::where('name', 'pending')->first()->id,
                    // 1 months after recived this techtest at point 5.
                    'expired_at' => Carbon::make('2021-10-13 23:59:59')
                ])));
            });

            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();

            return redirect()->back()->withError('Something went wrong.');
        }

        return redirect()->back()->withSuccess('The link has been generated.');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/invitations/index.blade.php
@extends('layouts.dashboard', ['pageTitle' => 'Invitations - Dashboard'])
@section('main')
<div class="flex justify-between items-center">
    <div class="w-1/2">
        <dashboard-breadcrumbs :items="[
        {
            text: 'Home',
            is_active: true,
            to: 'dashboard.index',
        },
        {
            text: 'Invitations',
        }
    ]">

        </dashboard-breadcrumbs>
    </div>
    <div class="w-1/2 flex justify-end">
        <btn type="submit" class="bg-blue-500 text-white" @click="() => this.$refs.$modal.showModal()">Generate Link</btn>
    </div>
</div>
<card>
    <invitation-tbl />
</card>
<modal :initshow="{{ $errors->has('email') ? 'true' : 'false' }}" :with-padding-y="false" :style="{'--width': `${window.innerWidth > 600 ? window.innerWidth / 2.5 : window.innerWidth / 1.2}px`, margin: 'auto'}" ref="$modal">
    <template v-slot:header>
        <h3>Generate Link</h3>
    </template>
    <template>
        <form method="POST" class="py-5 flex flex-col gap-6" action="{{ route('dashboard.invitations.generate') }}">
            @csrf
            <div>
                <text-input :errors='@json($errors->get("email"))' :input-props="{ name: 'email', placeholder: 'E-mail', autocomplete: 'off' }" value="{{ old('email') }}" placeholder="E-mail"></text-input>
            </div>
            <div class="flex justify-end mt-4 gap-2.5">
                <btn type="button" class="bg-gray-200 text-gray-500" @click="() => this.$refs.$modal.showModal(false)">Close</btn>
                <btn type="submit" class="bg-blue-500 text-white">Generate</btn>
            </div>
        </form>
    </template>
</modal>
@stop